version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartinv_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /clave-servicio.json
    restart: unless-stopped
